theme: jekyll-theme-slate
title: Geant4 Zero to Hero
description: Dev Space for End Users
google_analytics: G-GWLWQKHS6W
exclude:
  - 11
  - datasets/G4*
  - datasets/*6*
  - datasets/*2*
  - examples/gears
  - examples/mingle
  - examples/QF
  - examples/pct
  - run/shine
  - compose.yml
